name=ArduinoEvents
version=0.1.0
author=Daniele Cloralio <daniele.cloralio@gmail.com>
maintainer=Daniele Cloralio <daniele.cloralio@gmail.com>
sentence=Arduino class to implement asynchronous Zephyr events.
paragraph=This library provides an easy way to handle asynchronous events in Arduino sketches using the Zephyr event model.
category=Other
url=https://github.com/dani-clo/ArduinoEvents
architectures=zephyr
includes=ArduinoEvents.h
depends=
