name=RunAsyncEvents
version=0.1.0
author=Daniele Cloralio <daniele.cloralio@gmail.com>
maintainer=Daniele Cloralio <daniele.cloralio@gmail.com>
sentence=Arduino library to implement asynchronous Zephyr events.
paragraph=This is a lightweight event-driven library that provides a simple way to register callbacks and emit events, manage timers and async operations in Arduino sketches.
category=Other
url=https://github.com/dani-clo/ArduinoEvents
architectures=zephyr,zephyr_main,zephyr_contrib
includes=RunAsyncEvents.h
depends=
